export enum UserRole {
  ADMIN = 'ADMIN',
  CALLING_STAFF = 'CALLING_STAFF',
  SALESPERSON = 'SALESPERSON',
  PROJECT_HEAD = 'PROJECT_HEAD',
  DOCUMENTATION = 'DOCUMENTATION',
  WAREHOUSE = 'WAREHOUSE',
  INSTALLATION = 'INSTALLATION',
  ACCOUNTANT = 'ACCOUNTANT',
  DEALER_ADMIN = 'DEALER_ADMIN',
  DEALER_STAFF = 'DEALER_STAFF'
}

export enum ProjectStatus {
  LEAD = 'LEAD',
  SITE_SURVEY = 'SITE_SURVEY',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  PERMITTING = 'PERMITTING',
  INSTALLATION = 'INSTALLATION',
  INSPECTION = 'INSPECTION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum NotificationType {
  // Legacy
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  // Calling / Leads
  FOLLOW_UP_DUE = 'FOLLOW_UP_DUE',
  CAMPAIGN_STARTED = 'CAMPAIGN_STARTED',
  CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED',
  NEW_LEAD_ASSIGNED = 'NEW_LEAD_ASSIGNED',
  // Visits
  VISIT_SCHEDULED = 'VISIT_SCHEDULED',
  VISIT_REMINDER_1HR = 'VISIT_REMINDER_1HR',
  CHECKIN_REMINDER = 'CHECKIN_REMINDER',
  // Documentation
  NEW_CUSTOMER_ASSIGNED = 'NEW_CUSTOMER_ASSIGNED',
  CHECKLIST_UPDATED = 'CHECKLIST_UPDATED',
  CHECKLIST_COMPLETE = 'CHECKLIST_COMPLETE',
  // Finance
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  INVOICE_SENT = 'INVOICE_SENT',
  INVOICE_OVERDUE = 'INVOICE_OVERDUE',
  // Warehouse / Dispatch
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
  BOM_RECEIVED = 'BOM_RECEIVED',
  DISPATCH_READY = 'DISPATCH_READY',
  DISPATCHED = 'DISPATCHED',
  // Installation
  INSTALLATION_COMPLETE = 'INSTALLATION_COMPLETE',
  // Escalations
  TASK_DELAY_2D = 'TASK_DELAY_2D',
  TASK_DELAY_4D = 'TASK_DELAY_4D',
  // Proposals
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  PROPOSAL_ACCEPTED = 'PROPOSAL_ACCEPTED',
  // Admin
  DEALER_CREATED = 'DEALER_CREATED',
  USER_CREATED = 'USER_CREATED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
